### ISSUE TITLE
Form textbox needs improvement

### ISSUE THREAD

**Issue by phentos** [cse110-sp23-group1/magic8ball#15]
The color of the placeholder text does not contrast well with the background color. Maybe make the background color a little lighter and make both the placeholder text and the regular text black. It'll be better that way for accessibility. Also add `outline: none` to get rid of the default blue outline.

<img width="624" alt="Screen Shot 2023-04-23 at 2 42 36 PM" src="https://user-images.githubusercontent.com/72187062/233867788-f455bce7-ee16-46e1-ad0a-054064e803b8.png">

_Originally posted by @parth4apple in https://github.com/cse110-sp23-group1/magic8ball/pull/3#discussion_r1174657830_

**Comment by christiansulaiman** [comment]
Changes have been pushed to the branch

**Comment by phentos** [comment]
In the future @christiansulaiman reference the issue in commit ("attempted fix for #15" for example), it'll show up in the issue automatically, then close automatically when its branch is sent to main

if you were confident that you'd fixed it, you can use one of the keywords from the closure list like "fixes #15" and it will immediately close the issue when you commit
